### ISSUE TITLE
sobre la solució 

### ISSUE THREAD

**Issue by classicoman2** [yannickbf-prog/Exercicis_DWEC#1]
Hola Yannick,

a classe vaig explicar que en principi, tots els exercicis haurien d'estar en 1 sol fitxer .js, implementats en forma de funció i aquestes funcions s'havien de cridar des dels botons de la pantalla creada amb HTML. 
És millor fer això per a trobar errors i en general per l'aprenentatge que crear tants fitxers.

**Comment by yannickbf-prog** [comment]
Hola Toni

D'acord es vera que ho vas dir, no em vaig enrecordar, cuan tengui un moment em poso a cambiar-ho
